# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RIBs-Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RIBs', :git => 'https://github.com/uber/ribs-ios.git', :tag => 'v0.16.3'
  pod 'RxCocoa'
end
